[General]
network = StopAndWaitNetwork
sim-time-limit = 1000s

# Network-level parameters.
*.channelDelay = 0.05s
*.channelDatarate = 1Mbps
*.channelError = 0.1      # 10% packet (per) error
*.senderTimeout = 0.5s    # Sender's timeout. Must be > 2 * channelDelay
*.totalPackets = 10       # Total packets for each sender
