//
// Generated file, do not edit! Created by opp_msgtool 6.2 from packet.msg.
//

#ifndef __BASICROUTINGSIM_PACKET_M_H
#define __BASICROUTINGSIM_PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace BasicRoutingSim {

class SawPacket;

}  // namespace BasicRoutingSim

// cplusplus {{
#include <omnetpp.h>
// }}


namespace BasicRoutingSim {

/**
 * Enum generated from <tt>packet.msg:12</tt> by opp_msgtool.
 * <pre>
 * // Define packet types
 * enum PacketKind
 * {
 *     DATA_PACKET = 0;
 *     ACK_PACKET = 1;
 * }
 * </pre>
 */
enum PacketKind {
    DATA_PACKET = 0,
    ACK_PACKET = 1
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketKind& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketKind& e) { int n; b->unpack(n); e = static_cast<PacketKind>(n); }

/**
 * Class generated from <tt>packet.msg:17</tt> by opp_msgtool.
 * <pre>
 * packet SawPacket
 * {
 *     int kind; // Use PacketKind enum
 *     int sequenceNumber;
 *     string payload;
 *     int srcAddress;  // New
 *     int destAddress; // New
 * }
 * </pre>
 */
class SawPacket : public ::omnetpp::cPacket
{
  protected:
    int kind = 0;
    int sequenceNumber = 0;
    ::omnetpp::opp_string payload;
    int srcAddress = 0;
    int destAddress = 0;

  private:
    void copy(const SawPacket& other);

  protected:
    bool operator==(const SawPacket&) = delete;

  public:
    SawPacket(const char *name=nullptr, short kind=0);
    SawPacket(const SawPacket& other);
    virtual ~SawPacket();
    SawPacket& operator=(const SawPacket& other);
    virtual SawPacket *dup() const override {return new SawPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getKind() const;
    virtual void setKind(int kind);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress);

    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SawPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SawPacket& obj) {obj.parsimUnpack(b);}


}  // namespace BasicRoutingSim


namespace omnetpp {

template<> inline BasicRoutingSim::SawPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<BasicRoutingSim::SawPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __BASICROUTINGSIM_PACKET_M_H

